
CREATE TABLE IF NOT EXISTS GER_PESSOA (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
TIPO_PESSOA         ENUM('PF', 'PJ') NOT NULL,
DT_CADASTRO         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ATIVO               BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS GER_PESSOA_FISICA (
ID_PESSOA           INT PRIMARY KEY,
CPF                 VARCHAR(11) NOT NULL,
NOME                VARCHAR(200) NOT NULL,
DT_NASCIMENTO       DATE NULL,
TEL_CELULAR         VARCHAR(15) NULL,
CONSTRAINT UQ_PESSOA_FISICA_CPF UNIQUE (CPF),
CONSTRAINT FK_PESSOA_FISICA_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES GER_PESSOA(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS GER_PESSOA_JURIDICA (
ID_PESSOA           INT PRIMARY KEY,
CNPJ                VARCHAR(14) NOT NULL,
RAZAO_SOCIAL        VARCHAR(300) NOT NULL,
NOME_FANTASIA       VARCHAR(200) NULL,
INSCRICAO_ESTADUAL  VARCHAR(20) NULL,
INSCRICAO_MUNICIPAL VARCHAR(20) NULL,
TELEFONE            VARCHAR(15) NULL,
NATUREZA_JURIDICA   ENUM('MEI','LTDA','SA','ASSOCIACAO','FUNDACAO','COOPERATIVA','COLETIVO_INFORMAL') NULL,
PORTE               ENUM('MEI','MICROEMPRESA','PEQUENO_PORTE','MEDIO_GRANDE') NULL,
ANO_FUNDACAO        INT NULL,
MUNICIPIO_SEDE      VARCHAR(100) NULL,
QTD_MEMBROS         ENUM('1','2_A_5','6_A_20','21_A_50','MAIS_DE_50') NULL,
CONSTRAINT UQ_PESSOA_JURIDICA_CNPJ UNIQUE (CNPJ),
CONSTRAINT FK_PESSOA_JURIDICA_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES GER_PESSOA(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ENDERECO (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
ID_PESSOA           INT NOT NULL,
CEP                 VARCHAR(8) NULL,
LOGRADOURO          VARCHAR(300) NOT NULL,
NUMERO              VARCHAR(10) NULL,
SEM_NUMERO          BOOLEAN NOT NULL DEFAULT FALSE,
COMPLEMENTO         VARCHAR(100) NULL,
BAIRRO              VARCHAR(100) NOT NULL,
CIDADE              VARCHAR(100) NOT NULL,
UF                  VARCHAR(2) NOT NULL,
TIPO_ENDERECO       ENUM('RESIDENCIAL','COMERCIAL','SEDE') NULL,
LATITUDE            DECIMAL(10,8) NULL,
LONGITUDE           DECIMAL(11,8) NULL,
CONSTRAINT FK_ENDERECO_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES GER_PESSOA(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PORTAL_USERS (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
ID_PESSOA           INT NOT NULL,
CPF_CNPJ            VARCHAR(14) NOT NULL,
NOME                VARCHAR(200) NOT NULL,
EMAIL               VARCHAR(200) NOT NULL,
SENHA               VARCHAR(255) NOT NULL,
TEL_CELULAR         VARCHAR(15) NULL,
DT_NASCIMENTO       DATE NULL,
ATIVO               ENUM('S','N','B','P') NOT NULL DEFAULT 'P' COMMENT 'S=Ativo, N=Inativo, B=Bloqueado, P=Pendente',
DT_CADASTRO         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
DT_ATIVACAO         DATETIME NULL,
TOKEN_ATIVACAO      VARCHAR(100) NULL,
DT_TOKEN_ATIVACAO   DATETIME NULL,
TOKEN_RESET         VARCHAR(100) NULL,
DT_TOKEN_RESET      DATETIME NULL,
DT_ACEITE_TERMO     DATETIME NULL,
TENTATIVAS_FALHAS   INT NOT NULL DEFAULT 0,
DT_BLOQUEIO         DATETIME NULL,
OBSERVACAO_ADMIN    TEXT NULL,
CONSTRAINT UQ_PORTAL_USERS_CPF UNIQUE (CPF_CNPJ),
CONSTRAINT UQ_PORTAL_USERS_EMAIL UNIQUE (EMAIL),
CONSTRAINT FK_PORTAL_USERS_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES GER_PESSOA(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PORTAL_USERS_LOG (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
ID_PORTAL_USER      INT NOT NULL,
DT_ACAO             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
USUARIO_RESPONSAVEL VARCHAR(100) NOT NULL,
TIPO_ACAO           VARCHAR(50) NOT NULL COMMENT 'ATIVACAO, INATIVACAO, BLOQUEIO, RESET_SENHA, REENVIO_ATIVACAO, LOGIN, LOGIN_FALHA',
DESCRICAO           TEXT NULL,
IP_ORIGEM           VARCHAR(45) NULL,
USER_AGENT          VARCHAR(500) NULL,
CONSTRAINT FK_PORTAL_LOG_USER FOREIGN KEY (ID_PORTAL_USER) REFERENCES PORTAL_USERS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IDX_PORTAL_LOG_USER ON PORTAL_USERS_LOG(ID_PORTAL_USER);
CREATE INDEX IDX_PORTAL_LOG_DT ON PORTAL_USERS_LOG(DT_ACAO);

CREATE TABLE IF NOT EXISTS AREA_CULTURAL (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
CODIGO              VARCHAR(30) NOT NULL,
NOME                VARCHAR(100) NOT NULL,
ID_AREA_PAI         INT NULL,
ATIVO               BOOLEAN NOT NULL DEFAULT TRUE,
CONSTRAINT UQ_AREA_CULTURAL_CODIGO UNIQUE (CODIGO),
CONSTRAINT FK_AREA_PAI FOREIGN KEY (ID_AREA_PAI) REFERENCES AREA_CULTURAL(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS AGENTE_CULTURAL_PERFIL (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
ID_PESSOA           INT NOT NULL,
TIPO_PERFIL         ENUM('PF','PJ') NOT NULL,
BIOGRAFIA           TEXT NOT NULL,
TEMPO_ATUACAO       ENUM('MENOS_1_ANO','1_A_3','3_A_5','5_A_10','MAIS_10') NOT NULL,
ATUACAO_PROJETOS_SOCIAIS BOOLEAN NULL DEFAULT FALSE,
NOME_ARTISTICO      VARCHAR(100) NULL,
PRONOME_TRATAMENTO  ENUM('ELE_DELE','ELA_DELA','PREFIRO_NAO_INFORMAR') NULL,
GENERO              VARCHAR(50) NULL,
RACA_ETNIA          VARCHAR(50) NULL,
PCD                 VARCHAR(50) NULL,
MUNICIPIO_ATUACAO   VARCHAR(100) NOT NULL,
FOTO_PERFIL         VARCHAR(500) NULL,
HISTORICO_ORGANIZACAO TEXT NULL,
PUBLICO_ALVO        JSON NULL,
PUBLICIZACAO_AUTORIZADA BOOLEAN NOT NULL DEFAULT FALSE,
DATA_CONSENTIMENTO  DATETIME NULL,
ACEITE_VERACIDADE   BOOLEAN NOT NULL DEFAULT FALSE,
DATA_ACEITE_VERACIDADE DATETIME NULL,
STATUS_PERFIL       ENUM('ATIVO','PENDENTE','SUSPENSO','EXCLUIDO') NOT NULL DEFAULT 'ATIVO',
DT_CRIACAO          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
DT_ATUALIZACAO      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSENTIMENTO_MAPA_CULTURA BOOLEAN NOT NULL DEFAULT FALSE,
DATA_CONSENTIMENTO_MAPA DATETIME NULL,
CONSTRAINT FK_PERFIL_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES GER_PESSOA(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IDX_PERFIL_PESSOA ON AGENTE_CULTURAL_PERFIL(ID_PESSOA);
CREATE INDEX IDX_PERFIL_STATUS ON AGENTE_CULTURAL_PERFIL(STATUS_PERFIL);

CREATE TABLE IF NOT EXISTS AGENTE_AREA_CULTURAL (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
ID_AGENTE           INT NOT NULL,
ID_AREA             INT NOT NULL,
CONSTRAINT FK_AGENTE_AREA_AGENTE FOREIGN KEY (ID_AGENTE) REFERENCES AGENTE_CULTURAL_PERFIL(ID),
CONSTRAINT FK_AGENTE_AREA_AREA FOREIGN KEY (ID_AREA) REFERENCES AREA_CULTURAL(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS HABILIDADE (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
NOME                VARCHAR(100) NOT NULL,
TIPO                ENUM('HABILIDADE','FERRAMENTA','IDIOMA') NULL,
CONSTRAINT UQ_HABILIDADE_NOME UNIQUE (NOME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS AGENTE_HABILIDADE (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
ID_AGENTE           INT NOT NULL,
ID_HABILIDADE       INT NOT NULL,
NIVEL               ENUM('BASICO','INTERMEDIARIO','AVANCADO','FLUENTE') NULL,
DESCRICAO           VARCHAR(300) NULL,
CONSTRAINT FK_AGENTE_HAB_AGENTE FOREIGN KEY (ID_AGENTE) REFERENCES AGENTE_CULTURAL_PERFIL(ID),
CONSTRAINT FK_AGENTE_HAB_HAB FOREIGN KEY (ID_HABILIDADE) REFERENCES HABILIDADE(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PORTFOLIO (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
ID_AGENTE           INT NOT NULL,
TITULO              VARCHAR(150) NOT NULL,
TIPO                ENUM('ESPETACULO','EXPOSICAO','PUBLICACAO','ALBUM','FILME','PROJETO_SOCIAL','FESTIVAL','RESIDENCIA','OUTRO') NOT NULL,
ANO                 INT NOT NULL,
DESCRICAO           TEXT NULL,
LINK                VARCHAR(500) NULL,
CONSTRAINT FK_PORTFOLIO_AGENTE FOREIGN KEY (ID_AGENTE) REFERENCES AGENTE_CULTURAL_PERFIL(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PRESENCA_DIGITAL (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
ID_AGENTE           INT NOT NULL,
SITE_BLOG           VARCHAR(500) NULL,
INSTAGRAM           VARCHAR(100) NULL,
FACEBOOK            VARCHAR(500) NULL,
YOUTUBE             VARCHAR(500) NULL,
SPOTIFY_SOUNDCLOUD  VARCHAR(500) NULL,
VIMEO               VARCHAR(500) NULL,
OUTRO_LINK          VARCHAR(500) NULL,
CONSTRAINT FK_PRESENCA_AGENTE FOREIGN KEY (ID_AGENTE) REFERENCES AGENTE_CULTURAL_PERFIL(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS FORMACAO (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
ID_AGENTE           INT NOT NULL,
CATEGORIA           ENUM('ACADEMICA','CURSO_LIVRE','OFICINA','RESIDENCIA','NOTORIO_SABER','SABERES_TRADICIONAIS') NOT NULL,
TITULO              VARCHAR(200) NOT NULL,
INSTITUICAO         VARCHAR(200) NOT NULL,
CARGA_HORARIA       INT NULL,
ANO_CONCLUSAO       INT NULL,
STATUS_FORMACAO     ENUM('CONCLUIDO','EM_ANDAMENTO','INTERROMPIDO') NOT NULL DEFAULT 'CONCLUIDO',
DESCRICAO_SABER     TEXT NULL,
COMPROVANTE_PATH    VARCHAR(500) NULL,
CONSTRAINT FK_FORMACAO_AGENTE FOREIGN KEY (ID_AGENTE) REFERENCES AGENTE_CULTURAL_PERFIL(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS REPRESENTANTE_LEGAL (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
ID_PESSOA_JURIDICA  INT NOT NULL,
ID_USUARIO          INT NULL,
NOME                VARCHAR(200) NOT NULL,
CARGO               VARCHAR(100) NOT NULL,
RG                  VARCHAR(20) NULL,
CPF                 VARCHAR(11) NOT NULL,
TELEFONE            VARCHAR(15) NULL,
EMAIL               VARCHAR(200) NULL,
EH_SOCIO            BOOLEAN NOT NULL DEFAULT FALSE,
ORIGEM_PERFIL       ENUM('AGENTE_PJ','CONTRIBUINTE_CI','GRUPO_COLETIVO') NOT NULL,
DT_VINCULO          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
DT_DESVINCULACAO    DATETIME NULL,
ATIVO               BOOLEAN NOT NULL DEFAULT TRUE,
STATUS_VALIDACAO    ENUM('PENDENTE','APROVADO','RECUSADO') NOT NULL DEFAULT 'PENDENTE',
CONSTRAINT FK_REPR_PJ FOREIGN KEY (ID_PESSOA_JURIDICA) REFERENCES GER_PESSOA_JURIDICA(ID_PESSOA),
CONSTRAINT FK_REPR_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES PORTAL_USERS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS RESPONSAVEL_CADASTRO (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
ID_PESSOA_JURIDICA  INT NOT NULL,
ID_USUARIO          INT NOT NULL,
CARGO               VARCHAR(100) NOT NULL,
STATUS_VALIDACAO    ENUM('PENDENTE','APROVADO','RECUSADO') NOT NULL DEFAULT 'PENDENTE',
DT_SOLICITACAO      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
DT_VALIDACAO        DATETIME NULL,
ORIGEM_PERFIL       ENUM('AGENTE_PJ','CONTRIBUINTE_CI','GRUPO_COLETIVO') NOT NULL,
ATIVO               BOOLEAN NOT NULL DEFAULT TRUE,
CONSTRAINT FK_RESP_PJ FOREIGN KEY (ID_PESSOA_JURIDICA) REFERENCES GER_PESSOA_JURIDICA(ID_PESSOA),
CONSTRAINT FK_RESP_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES PORTAL_USERS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS DOCUMENTO_TIPO (
DOC_TIPO_ID         INT AUTO_INCREMENT PRIMARY KEY,
DOC_TIPO_NOME       VARCHAR(200) NOT NULL,
DOC_TIPO_CODIGO     VARCHAR(50) NOT NULL,
DOC_TIPO_DESCRICAO  TEXT NULL,
DOC_TIPO_CATEGORIA  ENUM('FISCAL','PESSOAL','TECNICO','JURIDICO') NOT NULL,
DOC_TIPO_TEMPORALIDADE BOOLEAN NOT NULL DEFAULT FALSE,
DOC_TIPO_PRAZO_VALIDADE INT NULL,
DOC_TIPO_UNIDADE_PRAZO ENUM('DIAS','MESES') NULL,
DOC_TIPO_ALERTA_VENCIMENTO INT NULL DEFAULT 30,
DOC_TIPO_FORMATOS   VARCHAR(50) NOT NULL DEFAULT 'PDF',
DOC_TIPO_TAMANHO_MAX_MB INT NOT NULL DEFAULT 10,
DOC_TIPO_MULTIPLOS_ARQUIVOS BOOLEAN NOT NULL DEFAULT FALSE,
DOC_TIPO_CONDICIONAL TEXT NULL,
DOC_TIPO_DT_INICIO_VIGENCIA DATE NOT NULL,
DOC_TIPO_DT_FIM_VIGENCIA DATE NULL,
DOC_TIPO_ORDEM      INT NULL DEFAULT 0,
DOC_TIPO_STATUS     ENUM('ATIVO','INATIVO','VIGENCIA_FUTURA') NOT NULL DEFAULT 'ATIVO',
CONSTRAINT UQ_DOC_TIPO_NOME UNIQUE (DOC_TIPO_NOME),
CONSTRAINT UQ_DOC_TIPO_CODIGO UNIQUE (DOC_TIPO_CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS DOCUMENTO_TIPO_PERFIL (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
ID_DOCUMENTO_TIPO   INT NOT NULL,
PERFIL              ENUM('PF','PJ','MEI','AGENTE_CULTURAL','INCENTIVADOR') NOT NULL,
OBRIGATORIO         BOOLEAN NOT NULL DEFAULT FALSE,
CONSTRAINT FK_DOC_TIPO_PERFIL_TIPO FOREIGN KEY (ID_DOCUMENTO_TIPO) REFERENCES DOCUMENTO_TIPO(DOC_TIPO_ID),
CONSTRAINT UQ_DOC_TIPO_PERFIL UNIQUE (ID_DOCUMENTO_TIPO, PERFIL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS DOCUMENTO (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
DOC_TIPO_ID         INT NOT NULL,
ID_PESSOA           INT NULL,
ID_INSCRICAO        INT NULL,
ID_RESPONSAVEL_CADASTRO INT NULL,
NOME_ARQUIVO        VARCHAR(300) NOT NULL,
PATH_ARQUIVO        VARCHAR(500) NOT NULL,
TIPO_ARQUIVO        VARCHAR(10) NOT NULL,
TAMANHO_BYTES       INT NOT NULL,
TIPO_ASSINATURA     ENUM('FISICA','DIGITAL_ICP','NAO_APLICAVEL') NULL,
STATUS_VALIDACAO    ENUM('PENDENTE','VALIDO','INVALIDO') NOT NULL DEFAULT 'PENDENTE',
DT_UPLOAD           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
DT_VALIDACAO        DATETIME NULL,
DT_EMISSAO          DATE NULL,
DT_VENCIMENTO       DATE NULL,
CONSTRAINT FK_DOCUMENTO_TIPO FOREIGN KEY (DOC_TIPO_ID) REFERENCES DOCUMENTO_TIPO(DOC_TIPO_ID),
CONSTRAINT FK_DOCUMENTO_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES GER_PESSOA(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IDX_DOCUMENTO_TIPO ON DOCUMENTO(DOC_TIPO_ID);
CREATE INDEX IDX_DOCUMENTO_PESSOA ON DOCUMENTO(ID_PESSOA);

CREATE TABLE IF NOT EXISTS GRUPO_DESPESA (
ID_GRUPO_DESPESA    INT AUTO_INCREMENT PRIMARY KEY,
NOME                VARCHAR(200) NOT NULL,
CODIGO_INTERNO      VARCHAR(50) NOT NULL,
DESCRICAO           TEXT NULL,
PERCENTUAL_MINIMO   DECIMAL(5,2) NULL DEFAULT 0,
PERCENTUAL_MAXIMO   DECIMAL(5,2) NULL DEFAULT 100,
INCIDE_IRRF         BOOLEAN NOT NULL DEFAULT FALSE,
ALIQUOTA_IRRF       DECIMAL(5,2) NULL,
ORDEM_EXIBICAO      INT NULL DEFAULT 0,
STATUS              ENUM('ATIVO','INATIVO') NOT NULL DEFAULT 'ATIVO',
CONSTRAINT UQ_GRUPO_DESPESA_CODIGO UNIQUE (CODIGO_INTERNO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS UNIDADE_MEDIDA (
ID_UNIDADE_MEDIDA   INT AUTO_INCREMENT PRIMARY KEY,
NOME                VARCHAR(100) NOT NULL,
SIGLA               VARCHAR(20) NOT NULL,
DESCRICAO           TEXT NULL,
STATUS              ENUM('ATIVO','INATIVO') NOT NULL DEFAULT 'ATIVO',
CONSTRAINT UQ_UNIDADE_SIGLA UNIQUE (SIGLA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ITEM_DESPESA (
ID_ITEM_DESPESA     INT AUTO_INCREMENT PRIMARY KEY,
ID_GRUPO_DESPESA    INT NOT NULL,
NOME                VARCHAR(200) NOT NULL,
CODIGO_INTERNO      VARCHAR(50) NOT NULL,
ELEGIVEL_IRRF       BOOLEAN NOT NULL DEFAULT TRUE,
PERMITE_VALOR_LIVRE BOOLEAN NOT NULL DEFAULT TRUE,
VALOR_UNITARIO_MAXIMO DECIMAL(15,2) NULL,
STATUS              ENUM('ATIVO','INATIVO','PENDENTE') NOT NULL DEFAULT 'ATIVO',
ID_USUARIO_SUGESTAO INT NULL COMMENT 'Usuario que sugeriu o item (quando PENDENTE)',
DT_SUGESTAO         DATETIME NULL,
CONSTRAINT UQ_ITEM_DESPESA_CODIGO UNIQUE (CODIGO_INTERNO),
CONSTRAINT FK_ITEM_GRUPO FOREIGN KEY (ID_GRUPO_DESPESA) REFERENCES GRUPO_DESPESA(ID_GRUPO_DESPESA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ITEM_UNIDADE (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
ID_ITEM_DESPESA     INT NOT NULL,
ID_UNIDADE_MEDIDA   INT NOT NULL,
CONSTRAINT FK_ITEM_UNIDADE_ITEM FOREIGN KEY (ID_ITEM_DESPESA) REFERENCES ITEM_DESPESA(ID_ITEM_DESPESA),
CONSTRAINT FK_ITEM_UNIDADE_UNIDADE FOREIGN KEY (ID_UNIDADE_MEDIDA) REFERENCES UNIDADE_MEDIDA(ID_UNIDADE_MEDIDA),
CONSTRAINT UQ_ITEM_UNIDADE UNIQUE (ID_ITEM_DESPESA, ID_UNIDADE_MEDIDA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS EDITAL (
ID_EDITAL           INT AUTO_INCREMENT PRIMARY KEY,
TITULO              VARCHAR(300) NOT NULL,
NUMERO              VARCHAR(50) NOT NULL,
ANO_REFERENCIA      INT NOT NULL,
DT_ABERTURA         DATE NOT NULL,
DT_ENCERRAMENTO     DATE NOT NULL,
TIPO_FOMENTO        ENUM('DIRETO','INDIRETO') NOT NULL,
VALOR_TOTAL         DECIMAL(15,2) NOT NULL,
PRAZO_INSCRICAO_INICIO DATETIME NOT NULL,
PRAZO_INSCRICAO_FIM DATETIME NOT NULL,
TEXTO_INFORMATIVO   TEXT NULL,
LIMITE_PROJETOS_POR_PRODUTOR INT NOT NULL DEFAULT 1,
DT_LIBERACAO_PARECER DATE NULL,
PERIODO_RECURSOS    INT NULL COMMENT 'Dias uteis',
PERIODO_CONTRARRAZOES INT NULL COMMENT 'Dias uteis',
PERIODO_PRORROGACAO_PROJETO INT NULL COMMENT 'Dias uteis',
PRORROGAVEL         BOOLEAN NOT NULL DEFAULT FALSE,
ENCERRAMENTO_AUTOMATICO ENUM('S','N') NOT NULL DEFAULT 'S',
STATUS              ENUM('RASCUNHO','EM_REVISAO','PUBLICADO','ENCERRADO','ARQUIVADO') NOT NULL DEFAULT 'RASCUNHO',
-- Fomento Direto
QTD_MAX_PROJETOS    INT NULL,
VALOR_MAX_PROJETO   DECIMAL(15,2) NULL,
PRAZO_EXECUCAO      INT NULL COMMENT 'Meses',
COMISSAO_AVALIADORA BOOLEAN NULL DEFAULT FALSE,
FASE_RECURSOS       BOOLEAN NULL DEFAULT FALSE,
PRESTACAO_CONTAS    BOOLEAN NULL DEFAULT FALSE,
TERRITORIALIZACAO   TEXT NULL,
-- Fomento Indireto
SUBTIPO_INDIRETO    ENUM('LEI_ISS','PATROCINIO') NULL,
LIMITE_RENUNCIA_FISCAL DECIMAL(15,2) NULL,
VALOR_MAX_CONTRIBUINTE DECIMAL(15,2) NULL,
VALOR_GRUPO_ECONOMICO DECIMAL(15,2) NULL,
ANO_EXERCICIO_ISS   INT NULL,
TIPO_EDITAL_ISS     ENUM('PRODUTOR_CULTURAL','CONTRIBUINTE_INCENTIVADOR') NULL,
PCT_MAX_ISS_CONTRIBUINTE DECIMAL(5,2) NULL DEFAULT 20,
-- Orcamento
HABILITAR_ORCAMENTO BOOLEAN NOT NULL DEFAULT FALSE,
CALCULAR_IMPOSTO_RETIDO BOOLEAN NOT NULL DEFAULT FALSE,
PERMITIR_SUGESTAO_ITENS BOOLEAN NOT NULL DEFAULT FALSE,
-- Formulario
ID_FORMULARIO_INSCRICAO INT NULL,
-- Publicacao
DT_PUBLICACAO_DO    DATE NULL,
NUMERO_DO           VARCHAR(50) NULL,
-- Elegibilidade
TIPOLOGIA_AGENTE    VARCHAR(500) NULL,
CRITERIOS_ELEGIBILIDADE TEXT NULL,
-- Auditoria
DT_CRIACAO          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
DT_ATUALIZACAO      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT UQ_EDITAL_NUMERO UNIQUE (NUMERO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IDX_EDITAL_STATUS ON EDITAL(STATUS);
CREATE INDEX IDX_EDITAL_TIPO ON EDITAL(TIPO_FOMENTO);

CREATE TABLE IF NOT EXISTS EDITAL_CATEGORIA (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
ID_EDITAL           INT NOT NULL,
NOME_CATEGORIA      VARCHAR(200) NOT NULL,
MODALIDADE          VARCHAR(200) NULL,
META_PROJETOS       INT NULL,
VALOR_POR_CATEGORIA DECIMAL(15,2) NULL,
CONSTRAINT FK_EDITAL_CAT_EDITAL FOREIGN KEY (ID_EDITAL) REFERENCES EDITAL(ID_EDITAL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS EDITAL_CRITERIO_AVALIACAO (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
ID_EDITAL           INT NOT NULL,
CRITERIO            VARCHAR(300) NOT NULL,
PESO                INT NOT NULL,
PERFIL_AVALIADOR    VARCHAR(200) NULL,
DESCRICAO           TEXT NULL,
CONSTRAINT FK_EDITAL_CRIT_EDITAL FOREIGN KEY (ID_EDITAL) REFERENCES EDITAL(ID_EDITAL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS EDITAL_DOCUMENTO (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
ID_EDITAL           INT NOT NULL,
DOC_TIPO_ID         INT NOT NULL,
OBRIGATORIO         BOOLEAN NOT NULL DEFAULT TRUE,
ID_CATEGORIA        INT NULL COMMENT 'Documento especifico por categoria (NULL = geral)',
CONSTRAINT FK_EDITAL_DOC_EDITAL FOREIGN KEY (ID_EDITAL) REFERENCES EDITAL(ID_EDITAL),
CONSTRAINT FK_EDITAL_DOC_TIPO FOREIGN KEY (DOC_TIPO_ID) REFERENCES DOCUMENTO_TIPO(DOC_TIPO_ID),
CONSTRAINT FK_EDITAL_DOC_CAT FOREIGN KEY (ID_CATEGORIA) REFERENCES EDITAL_CATEGORIA(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS EDITAL_GRUPO_DESPESA (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
ID_EDITAL           INT NOT NULL,
ID_GRUPO_DESPESA    INT NOT NULL,
PERCENTUAL_MIN      DECIMAL(5,2) NULL,
PERCENTUAL_MAX      DECIMAL(5,2) NULL,
CONSTRAINT FK_EDITAL_GD_EDITAL FOREIGN KEY (ID_EDITAL) REFERENCES EDITAL(ID_EDITAL),
CONSTRAINT FK_EDITAL_GD_GRUPO FOREIGN KEY (ID_GRUPO_DESPESA) REFERENCES GRUPO_DESPESA(ID_GRUPO_DESPESA),
CONSTRAINT UQ_EDITAL_GRUPO UNIQUE (ID_EDITAL, ID_GRUPO_DESPESA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS EDITAL_IMPOSTO_CONFIG (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
ID_EDITAL           INT NOT NULL,
INSTRUMENTO_JURIDICO VARCHAR(200) NOT NULL,
ALIQUOTA            DECIMAL(5,2) NOT NULL,
CONSTRAINT FK_EDITAL_IMP_EDITAL FOREIGN KEY (ID_EDITAL) REFERENCES EDITAL(ID_EDITAL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS EDITAL_IMPOSTO_GRUPO (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
ID_EDITAL_IMPOSTO   INT NOT NULL,
ID_GRUPO_DESPESA    INT NOT NULL,
CONSTRAINT FK_IMP_GRUPO_IMP FOREIGN KEY (ID_EDITAL_IMPOSTO) REFERENCES EDITAL_IMPOSTO_CONFIG(ID),
CONSTRAINT FK_IMP_GRUPO_GRUPO FOREIGN KEY (ID_GRUPO_DESPESA) REFERENCES GRUPO_DESPESA(ID_GRUPO_DESPESA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS FORMULARIO (
ID_FORMULARIO       INT AUTO_INCREMENT PRIMARY KEY,
NOME                VARCHAR(150) NOT NULL,
DESCRICAO           VARCHAR(500) NULL,
STATUS              ENUM('RASCUNHO','ATIVO','INATIVO','ARQUIVADO') NOT NULL DEFAULT 'RASCUNHO',
PERMITE_EDITAR_APOS_PUBLICACAO BOOLEAN NOT NULL DEFAULT FALSE,
TIPO_ACESSO         ENUM('PUBLICO','LOGADO') NOT NULL DEFAULT 'LOGADO',
ID_USUARIO_CRIADOR  INT NULL,
VERSAO_ATUAL        INT NOT NULL DEFAULT 1,
DT_CRIACAO          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
DT_ATUALIZACAO      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
DT_PUBLICACAO       DATETIME NULL,
LINK_PUBLICO        VARCHAR(500) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PAGINA (
ID_PAGINA           INT AUTO_INCREMENT PRIMARY KEY,
ID_FORMULARIO       INT NOT NULL,
TITULO              VARCHAR(200) NULL,
DESCRICAO           TEXT NULL,
ORDEM               INT NOT NULL DEFAULT 1,
DT_CRIACAO          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT FK_PAGINA_FORM FOREIGN KEY (ID_FORMULARIO) REFERENCES FORMULARIO(ID_FORMULARIO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS CAMPO (
ID_CAMPO            INT AUTO_INCREMENT PRIMARY KEY,
ID_FORMULARIO       INT NOT NULL,
ID_PAGINA           INT NOT NULL,
NOME                VARCHAR(100) NOT NULL,
LABEL               VARCHAR(300) NOT NULL,
TIPO_CAMPO          ENUM('TEXTO_CURTO','PARAGRAFO','NUMERO','MULTIPLA_ESCOLHA','CAIXAS_SELECAO','LISTA_SUSPENSA','DATA','UPLOAD') NOT NULL,
ORDEM               INT NOT NULL DEFAULT 1,
OBRIGATORIO         BOOLEAN NOT NULL DEFAULT FALSE,
OBRIGATORIO_CONDICIONAL BOOLEAN NOT NULL DEFAULT FALSE,
AUTO_PREENCHIVEL    BOOLEAN NOT NULL DEFAULT FALSE,
CAMPO_CADASTRO      VARCHAR(200) NULL,
PLACEHOLDER         VARCHAR(200) NULL,
TEXTO_AJUDA         VARCHAR(500) NULL,
VALIDACOES          JSON NULL,
DT_CRIACAO          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT FK_CAMPO_FORM FOREIGN KEY (ID_FORMULARIO) REFERENCES FORMULARIO(ID_FORMULARIO),
CONSTRAINT FK_CAMPO_PAGINA FOREIGN KEY (ID_PAGINA) REFERENCES PAGINA(ID_PAGINA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS CAMPO_OPCAO (
ID_OPCAO            INT AUTO_INCREMENT PRIMARY KEY,
ID_CAMPO            INT NOT NULL,
DESCRICAO           VARCHAR(300) NOT NULL,
VALOR               VARCHAR(200) NOT NULL,
ORDEM               INT NOT NULL DEFAULT 1,
CONSTRAINT FK_OPCAO_CAMPO FOREIGN KEY (ID_CAMPO) REFERENCES CAMPO(ID_CAMPO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS REGRA_VISIBILIDADE (
ID_REGRA            INT AUTO_INCREMENT PRIMARY KEY,
ID_FORMULARIO       INT NOT NULL,
ID_CAMPO_ALVO       INT NOT NULL,
ID_CAMPO_CONDICIONAL INT NOT NULL,
OPERADOR            VARCHAR(50) NOT NULL,
VALOR_CONDICIONAL   VARCHAR(500) NOT NULL,
ACAO                ENUM('EXIBIR','OCULTAR') NOT NULL DEFAULT 'EXIBIR',
ATIVO               BOOLEAN NOT NULL DEFAULT TRUE,
DT_CRIACAO          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT FK_REGRA_FORM FOREIGN KEY (ID_FORMULARIO) REFERENCES FORMULARIO(ID_FORMULARIO),
CONSTRAINT FK_REGRA_ALVO FOREIGN KEY (ID_CAMPO_ALVO) REFERENCES CAMPO(ID_CAMPO),
CONSTRAINT FK_REGRA_COND FOREIGN KEY (ID_CAMPO_CONDICIONAL) REFERENCES CAMPO(ID_CAMPO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS NAVEGACAO_CONDICIONAL (
ID_NAV              INT AUTO_INCREMENT PRIMARY KEY,
ID_FORMULARIO       INT NOT NULL,
PAGINA_ORIGEM       INT NOT NULL,
PAGINA_DESTINO      INT NOT NULL,
PAGINA_PADRAO       INT NULL,
ID_CAMPO_CONDICIONAL INT NOT NULL,
OPERADOR            VARCHAR(50) NOT NULL,
VALOR               VARCHAR(500) NOT NULL,
PRIORIDADE          INT NOT NULL DEFAULT 1,
DESCRICAO           VARCHAR(300) NULL,
ATIVO               BOOLEAN NOT NULL DEFAULT TRUE,
DT_CRIACAO          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT FK_NAV_FORM FOREIGN KEY (ID_FORMULARIO) REFERENCES FORMULARIO(ID_FORMULARIO),
CONSTRAINT FK_NAV_ORIGEM FOREIGN KEY (PAGINA_ORIGEM) REFERENCES PAGINA(ID_PAGINA),
CONSTRAINT FK_NAV_DESTINO FOREIGN KEY (PAGINA_DESTINO) REFERENCES PAGINA(ID_PAGINA),
CONSTRAINT FK_NAV_CAMPO FOREIGN KEY (ID_CAMPO_CONDICIONAL) REFERENCES CAMPO(ID_CAMPO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS VINCULACAO_CADASTRO (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
ID_FORMULARIO       INT NOT NULL,
ID_CAMPO            INT NOT NULL,
ID_ATRIBUTO_CADASTRO VARCHAR(200) NOT NULL,
EDITAVEL            BOOLEAN NOT NULL DEFAULT TRUE,
ATIVO               BOOLEAN NOT NULL DEFAULT TRUE,
CONSTRAINT FK_VINC_FORM FOREIGN KEY (ID_FORMULARIO) REFERENCES FORMULARIO(ID_FORMULARIO),
CONSTRAINT FK_VINC_CAMPO FOREIGN KEY (ID_CAMPO) REFERENCES CAMPO(ID_CAMPO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS LOG_AUDITORIA (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
ID_FORMULARIO       INT NOT NULL,
NUM_VERSAO          INT NOT NULL,
DT_HORA             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ID_USUARIO          INT NULL,
NOME_USUARIO        VARCHAR(200) NULL,
TIPO_ALTERACAO      VARCHAR(100) NOT NULL,
CAMPOS_ALTERADOS    JSON NULL,
VALOR_ANTERIOR      JSON NULL,
VALOR_ATUAL         JSON NULL,
DESCRICAO_ALTERACAO TEXT NULL,
CONSTRAINT FK_LOG_FORM FOREIGN KEY (ID_FORMULARIO) REFERENCES FORMULARIO(ID_FORMULARIO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IDX_LOG_FORM ON LOG_AUDITORIA(ID_FORMULARIO);
CREATE INDEX IDX_LOG_DT ON LOG_AUDITORIA(DT_HORA);

CREATE TABLE IF NOT EXISTS INSCRICAO (
ID_INSCRICAO        INT AUTO_INCREMENT PRIMARY KEY,
ID_FORMULARIO       INT NOT NULL,
ID_EDITAL           INT NULL,
ID_USUARIO          INT NOT NULL,
ID_PERFIL_CULTURAL  INT NOT NULL,
VERSAO_FORMULARIO   INT NOT NULL DEFAULT 1,
SNAPSHOT_PERFIL     JSON NULL,
STATUS              ENUM('RASCUNHO','ENVIADA','EM_ANALISE','HABILITADA','INABILITADA','EM_DILIGENCIA','EM_RECURSO','APROVADA','REPROVADA','READEQUACAO_SOLICITADA','READEQUACAO_SUBMETIDA') NOT NULL DEFAULT 'RASCUNHO',
TIPO_PERFIL_USADO   ENUM('PF','PJ','CI') NOT NULL,
VALOR_SOLICITADO    DECIMAL(15,2) NULL,
DT_CRIACAO          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
DT_SUBMISSAO        DATETIME NULL,
DT_ATUALIZACAO      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT FK_INSCRICAO_FORM FOREIGN KEY (ID_FORMULARIO) REFERENCES FORMULARIO(ID_FORMULARIO),
CONSTRAINT FK_INSCRICAO_EDITAL FOREIGN KEY (ID_EDITAL) REFERENCES EDITAL(ID_EDITAL),
CONSTRAINT FK_INSCRICAO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES PORTAL_USERS(ID),
CONSTRAINT FK_INSCRICAO_PERFIL FOREIGN KEY (ID_PERFIL_CULTURAL) REFERENCES AGENTE_CULTURAL_PERFIL(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IDX_INSCRICAO_EDITAL ON INSCRICAO(ID_EDITAL);
CREATE INDEX IDX_INSCRICAO_USUARIO ON INSCRICAO(ID_USUARIO);
CREATE INDEX IDX_INSCRICAO_STATUS ON INSCRICAO(STATUS);

CREATE TABLE IF NOT EXISTS INSCRICAO_STATUS_LOG (
ID_LOG              INT AUTO_INCREMENT PRIMARY KEY,
ID_INSCRICAO        INT NOT NULL,
STATUS_ANTERIOR     VARCHAR(50) NOT NULL,
STATUS_NOVO         VARCHAR(50) NOT NULL,
ID_USUARIO_RESPONSAVEL INT NOT NULL,
DT_HORA             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
OBSERVACAO          TEXT NULL,
MOTIVOS_INABILITACAO JSON NULL,
DOCUMENTOS_FALTANTES JSON NULL,
CONSTRAINT FK_STATUS_LOG_INSCRICAO FOREIGN KEY (ID_INSCRICAO) REFERENCES INSCRICAO(ID_INSCRICAO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IDX_STATUS_LOG_INSCRICAO ON INSCRICAO_STATUS_LOG(ID_INSCRICAO);

CREATE TABLE IF NOT EXISTS INSCRICAO_ORCAMENTO_VERSAO (
ID_VERSAO           INT AUTO_INCREMENT PRIMARY KEY,
ID_INSCRICAO        INT NOT NULL,
NUMERO_VERSAO       INT NOT NULL DEFAULT 1,
STATUS              ENUM('VIGENTE','SUBSTITUIDA','PENDENTE_APROVACAO','RECUSADA') NOT NULL DEFAULT 'VIGENTE',
TOTAL_GERAL         DECIMAL(15,2) NOT NULL DEFAULT 0,
TOTAL_IRRF          DECIMAL(15,2) NULL DEFAULT 0,
MOTIVO_READEQUACAO  TEXT NULL,
ID_USUARIO_RESPONSAVEL INT NOT NULL,
DT_CRIACAO          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
DT_DELIBERACAO      DATETIME NULL,
CONSTRAINT FK_ORC_VERSAO_INSCRICAO FOREIGN KEY (ID_INSCRICAO) REFERENCES INSCRICAO(ID_INSCRICAO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS INSCRICAO_ORCAMENTO_ITEM (
ID_ITEM             INT AUTO_INCREMENT PRIMARY KEY,
ID_VERSAO           INT NOT NULL,
ID_GRUPO_DESPESA    INT NOT NULL,
ID_ITEM_DESPESA     INT NOT NULL,
ID_UNIDADE_MEDIDA   INT NULL,
QUANTIDADE          INT NOT NULL DEFAULT 1,
QTD_UNIDADE         DECIMAL(10,2) NOT NULL DEFAULT 1,
VALOR_UNITARIO      DECIMAL(15,2) NOT NULL,
TOTAL_LINHA         DECIMAL(15,2) NOT NULL,
IRRF_LINHA          DECIMAL(15,2) NULL DEFAULT 0,
ITEM_SUGERIDO       BOOLEAN NOT NULL DEFAULT FALSE,
STATUS_SUGESTAO     ENUM('PENDENTE','APROVADO','RECUSADO') NULL,
CONSTRAINT FK_ORC_ITEM_VERSAO FOREIGN KEY (ID_VERSAO) REFERENCES INSCRICAO_ORCAMENTO_VERSAO(ID_VERSAO),
CONSTRAINT FK_ORC_ITEM_GRUPO FOREIGN KEY (ID_GRUPO_DESPESA) REFERENCES GRUPO_DESPESA(ID_GRUPO_DESPESA),
CONSTRAINT FK_ORC_ITEM_ITEM FOREIGN KEY (ID_ITEM_DESPESA) REFERENCES ITEM_DESPESA(ID_ITEM_DESPESA),
CONSTRAINT FK_ORC_ITEM_UNIDADE FOREIGN KEY (ID_UNIDADE_MEDIDA) REFERENCES UNIDADE_MEDIDA(ID_UNIDADE_MEDIDA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS RESPOSTA (
ID_RESPOSTA         INT AUTO_INCREMENT PRIMARY KEY,
ID_INSCRICAO        INT NOT NULL,
ID_CAMPO            INT NOT NULL,
VALOR               TEXT NULL,
CONSTRAINT FK_RESPOSTA_INSCRICAO FOREIGN KEY (ID_INSCRICAO) REFERENCES INSCRICAO(ID_INSCRICAO),
CONSTRAINT FK_RESPOSTA_CAMPO FOREIGN KEY (ID_CAMPO) REFERENCES CAMPO(ID_CAMPO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IDX_RESPOSTA_INSCRICAO ON RESPOSTA(ID_INSCRICAO);

CREATE TABLE IF NOT EXISTS LOG_ALTERACAO_PERFIL (
ID                  INT AUTO_INCREMENT PRIMARY KEY,
ID_PERFIL           INT NOT NULL,
ID_USUARIO          INT NOT NULL,
TIPO_OPERACAO       ENUM('EDICAO','DESVINCULACAO','EXCLUSAO') NOT NULL,
DT_HORA             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
CAMPO_ALTERADO      VARCHAR(200) NULL,
VALOR_ANTERIOR      TEXT NULL,
VALOR_NOVO          TEXT NULL,
SECAO_AFETADA       VARCHAR(200) NULL,
VISIBILIDADE_ANTERIOR VARCHAR(20) NULL,
VISIBILIDADE_NOVA   VARCHAR(20) NULL,
CONSTRAINT FK_LOG_PERFIL_PERFIL FOREIGN KEY (ID_PERFIL) REFERENCES AGENTE_CULTURAL_PERFIL(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IDX_LOG_PERFIL ON LOG_ALTERACAO_PERFIL(ID_PERFIL);

INSERT INTO AREA_CULTURAL (CODIGO, NOME) VALUES
('ARTES_CENICAS', 'Artes Cenicas'),
('ARTES_VISUAIS', 'Artes Visuais'),
('MUSICA', 'Musica'),
('LITERATURA', 'Livro e Literatura'),
('PATRIMONIO', 'Memoria e Patrimonio'),
('CULTURA_POPULAR', 'Cultura Popular');

INSERT INTO AREA_CULTURAL (CODIGO, NOME, ID_AREA_PAI) VALUES
('TEATRO', 'Teatro', (SELECT ID FROM AREA_CULTURAL WHERE CODIGO = 'ARTES_CENICAS')),
('DANCA', 'Danca', (SELECT ID FROM AREA_CULTURAL WHERE CODIGO = 'ARTES_CENICAS')),
('CIRCO', 'Circo', (SELECT ID FROM AREA_CULTURAL WHERE CODIGO = 'ARTES_CENICAS')),
('PERFORMANCE', 'Performance', (SELECT ID FROM AREA_CULTURAL WHERE CODIGO = 'ARTES_CENICAS')),
('PINTURA', 'Pintura', (SELECT ID FROM AREA_CULTURAL WHERE CODIGO = 'ARTES_VISUAIS')),
('ESCULTURA', 'Escultura', (SELECT ID FROM AREA_CULTURAL WHERE CODIGO = 'ARTES_VISUAIS')),
('FOTOGRAFIA', 'Fotografia', (SELECT ID FROM AREA_CULTURAL WHERE CODIGO = 'ARTES_VISUAIS')),
('GRAFITE', 'Grafite', (SELECT ID FROM AREA_CULTURAL WHERE CODIGO = 'ARTES_VISUAIS')),
('CINEMA', 'Cinema', (SELECT ID FROM AREA_CULTURAL WHERE CODIGO = 'ARTES_VISUAIS')),
('VIDEO', 'Video', (SELECT ID FROM AREA_CULTURAL WHERE CODIGO = 'ARTES_VISUAIS')),
('MPB', 'MPB', (SELECT ID FROM AREA_CULTURAL WHERE CODIGO = 'MUSICA')),
('SAMBA', 'Samba', (SELECT ID FROM AREA_CULTURAL WHERE CODIGO = 'MUSICA')),
('FUNK', 'Funk', (SELECT ID FROM AREA_CULTURAL WHERE CODIGO = 'MUSICA')),
('ERUDITA', 'Erudita', (SELECT ID FROM AREA_CULTURAL WHERE CODIGO = 'MUSICA')),
('POESIA', 'Poesia', (SELECT ID FROM AREA_CULTURAL WHERE CODIGO = 'LITERATURA')),
('CONTO', 'Conto', (SELECT ID FROM AREA_CULTURAL WHERE CODIGO = 'LITERATURA')),
('ROMANCE', 'Romance', (SELECT ID FROM AREA_CULTURAL WHERE CODIGO = 'LITERATURA')),
('PATRIMONIO_IMATERIAL', 'Patrimonio Imaterial', (SELECT ID FROM AREA_CULTURAL WHERE CODIGO = 'PATRIMONIO')),
('DOCUMENTACAO', 'Documentacao', (SELECT ID FROM AREA_CULTURAL WHERE CODIGO = 'PATRIMONIO')),
('RESTAURACAO', 'Restauracao', (SELECT ID FROM AREA_CULTURAL WHERE CODIGO = 'PATRIMONIO')),
('FOLCLORE', 'Folclore', (SELECT ID FROM AREA_CULTURAL WHERE CODIGO = 'CULTURA_POPULAR')),
('ARTESANATO', 'Artesanato', (SELECT ID FROM AREA_CULTURAL WHERE CODIGO = 'CULTURA_POPULAR')),
('FESTAS_POPULARES', 'Festas Populares', (SELECT ID FROM AREA_CULTURAL WHERE CODIGO = 'CULTURA_POPULAR')),
('CAPOEIRA', 'Capoeira', (SELECT ID FROM AREA_CULTURAL WHERE CODIGO = 'CULTURA_POPULAR'));
